#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# deploy.sh — Deploy Terminus GIS to the current host
#
# Called by GitLab CI or run manually. Reads configuration from environment
# variables (set by GitLab CI/CD variables or a local .env file).
#
# Usage:
#   # From GitLab CI (variables injected automatically):
#   ./deploy/deploy.sh
#
#   # Manual deploy with .env file:
#   cd lakehouse && source .env && cd .. && ./deploy/deploy.sh
###############################################################################

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
LAKEHOUSE_DIR="${PROJECT_ROOT}/lakehouse"

# ─── Required variables ───────────────────────────────────────────────
: "${S3_ACCESS_KEY_ID:?Set S3_ACCESS_KEY_ID}"
: "${S3_SECRET_ACCESS_KEY:?Set S3_SECRET_ACCESS_KEY}"
: "${S3_ENDPOINT:?Set S3_ENDPOINT}"
: "${S3_REGION:?Set S3_REGION}"
: "${S3_BUCKET:?Set S3_BUCKET}"

# ─── Defaults ─────────────────────────────────────────────────────────
DEPLOY_PROFILES="${DEPLOY_PROFILES:-agent}"
S3_URL_STYLE="${S3_URL_STYLE:-vhost}"
S3_USE_SSL="${S3_USE_SSL:-true}"
S3_PATH_STYLE="${S3_PATH_STYLE:-false}"
S3_FLAVOR="${S3_FLAVOR:-aws}"
BASEMAP_CONFIG="${BASEMAP_CONFIG:-basemaps.json}"
SA_LLM_BACKEND="${SA_LLM_BACKEND:-ollama}"
LAKEKEEPER_PG_ENCRYPTION_KEY="${LAKEKEEPER_PG_ENCRYPTION_KEY:-$(openssl rand -hex 32)}"
PYGEOAPI_SERVER_URL="${PYGEOAPI_SERVER_URL:-auto}"

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║   Terminus GIS — Deploy                      ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "  Profiles:  ${DEPLOY_PROFILES}"
echo "  S3:        ${S3_ENDPOINT} / ${S3_BUCKET}"
echo "  LLM:       ${SA_LLM_BACKEND}"
echo "  Basemaps:  ${BASEMAP_CONFIG}"
echo ""

# ─── 1. Write .env ────────────────────────────────────────────────────
echo "① Writing .env..."
cat > "${LAKEHOUSE_DIR}/.env" <<EOF
# Generated by deploy.sh — $(date -Iseconds 2>/dev/null || date)
S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
S3_ENDPOINT=${S3_ENDPOINT}
S3_REGION=${S3_REGION}
S3_BUCKET=${S3_BUCKET}
S3_URL_STYLE=${S3_URL_STYLE}
S3_USE_SSL=${S3_USE_SSL}
S3_PATH_STYLE=${S3_PATH_STYLE}
S3_FLAVOR=${S3_FLAVOR}
LAKEKEEPER_PG_ENCRYPTION_KEY=${LAKEKEEPER_PG_ENCRYPTION_KEY}
PYGEOAPI_SERVER_URL=${PYGEOAPI_SERVER_URL}
SA_LLM_BACKEND=${SA_LLM_BACKEND}
SA_BEDROCK_REGION=${SA_BEDROCK_REGION:-${S3_REGION}}
SA_BEDROCK_MODEL_ID=${SA_BEDROCK_MODEL_ID:-us.anthropic.claude-sonnet-4-20250514}
BASEMAP_CONFIG=${BASEMAP_CONFIG}
OLLAMA_MEM_LIMIT=${OLLAMA_MEM_LIMIT:-16g}
EOF
echo "   ✓ .env written."

# ─── 2. Build ─────────────────────────────────────────────────────────
echo "② Building images..."
cd "${LAKEHOUSE_DIR}"

# Build profile flags
PROFILE_FLAGS=""
for p in $DEPLOY_PROFILES; do
  PROFILE_FLAGS="${PROFILE_FLAGS} --profile ${p}"
done

docker compose ${PROFILE_FLAGS} build
echo "   ✓ Build complete."

# ─── 3. Deploy ────────────────────────────────────────────────────────
echo "③ Starting services..."
docker compose ${PROFILE_FLAGS} up -d
echo "   ✓ Services started."

# ─── 4. Bootstrap (idempotent) ────────────────────────────────────────
echo "④ Running bootstrap..."
./bootstrap.sh
echo "   ✓ Bootstrap complete."

# ─── 5. Pull Ollama model (if agent profile + ollama backend) ─────────
if echo "$DEPLOY_PROFILES" | grep -q "agent" && [ "$SA_LLM_BACKEND" = "ollama" ]; then
  echo "⑤ Checking Ollama model..."
  # Wait for Ollama to be ready
  for i in $(seq 1 30); do
    if docker compose exec -T ollama curl -sf http://localhost:11434/api/tags > /dev/null 2>&1; then
      break
    fi
    sleep 2
  done

  # Check if model already exists
  MODEL_EXISTS=$(docker compose exec -T ollama curl -sf http://localhost:11434/api/tags 2>/dev/null \
    | grep -c "devstral-small" || echo "0")

  if [ "$MODEL_EXISTS" = "0" ]; then
    echo "   Pulling devstral-small-2 (this may take a while)..."
    docker compose exec -T ollama ollama pull devstral-small-2
    echo "   ✓ Model pulled."
  else
    echo "   ✓ Model already available."
  fi
fi

# ─── 6. Health check ─────────────────────────────────────────────────
echo "⑥ Health checks..."
FAILED=0

check_health() {
  local url="$1" name="$2"
  for i in $(seq 1 15); do
    if curl -sf -o /dev/null "$url" 2>/dev/null; then
      echo "   ✓ ${name}"
      return 0
    fi
    sleep 2
  done
  echo "   ✗ ${name} — not responding"
  FAILED=$((FAILED + 1))
  return 0
}

check_health "http://localhost:8000/api/docs" "Feature API"
check_health "http://localhost:8181/health" "LakeKeeper"
check_health "http://localhost:80/" "Webmap"
check_health "http://localhost:8082/mcp" "MCP Server" || true  # 400/405 is OK

if echo "$DEPLOY_PROFILES" | grep -q "agent"; then
  check_health "http://localhost:8090/health" "Spatial Agent"
fi

# ─── Done ─────────────────────────────────────────────────────────────
echo ""
if [ "$FAILED" -gt 0 ]; then
  echo "⚠ Deploy completed with ${FAILED} failed health check(s)."
  echo "  Check: docker compose ${PROFILE_FLAGS} logs"
  exit 1
else
  echo "╔══════════════════════════════════════════════╗"
  echo "║   ✅  Deploy complete!                       ║"
  echo "╚══════════════════════════════════════════════╝"
fi
